-- Demo data for "Ember & Oak Coffee Roasters" (a fictional store). Applied by `supabase db reset`.
-- Knowledge base documents are loaded separately by `npm run ingest` (it needs the embedding API).

insert into public.products (sku, name, category, price_cents, stock_qty, description) values
('EO-COF-001', 'Ethiopia Guji Natural', 'coffee', 1850, 40,
 'Light roast single origin, 12 oz (340 g) whole bean. Grown around 2,000 m in Guji. Tastes of blueberry, jasmine and honey with a juicy, tea-like body. Best as pour-over or AeroPress.'),
('EO-COF-002', 'Colombia Huila Washed', 'coffee', 1650, 55,
 'Medium roast single origin, 12 oz (340 g) whole bean. Caramel, red apple and cocoa with a clean, balanced finish. A dependable daily brew for drip, pour-over and French press.'),
('EO-COF-003', 'Kenya AA Kiambu', 'coffee', 1950, 12,
 'Light to medium roast single origin, 12 oz (340 g) whole bean. Blackcurrant, grapefruit and brown sugar with bright, wine-like acidity. Rewarding as pour-over.'),
('EO-COF-004', 'Brazil Cerrado', 'coffee', 1500, 80,
 'Medium to dark roast single origin, 12 oz (340 g) whole bean. Hazelnut and dark chocolate with low acidity and a heavy body. Works well as espresso and in milk drinks.'),
('EO-COF-005', 'Guatemala Antigua', 'coffee', 1700, 33,
 'Medium roast single origin, 12 oz (340 g) whole bean. Cocoa, orange zest and toasted almond with a smooth, rounded body. Versatile across brew methods.'),
('EO-COF-006', 'Sumatra Mandheling', 'coffee', 1750, 0,
 'Dark roast single origin, 12 oz (340 g) whole bean. Earthy, with cedar and dark chocolate notes and a full, syrupy body. Low acidity, good in French press and moka pot.'),
('EO-COF-007', 'Ember House Blend', 'coffee', 1450, 120,
 'Medium roast blend, 12 oz (340 g) whole bean. Milk chocolate and toffee, smooth and easy drinking. Our everyday coffee for drip machines and French press.'),
('EO-COF-008', 'Oak Espresso Blend', 'coffee', 1600, 64,
 'Medium to dark roast blend built for espresso, 12 oz (340 g) whole bean. Dark chocolate, cherry and caramel with a thick crema. Also good in a moka pot.'),
('EO-COF-009', 'Swiss Water Decaf Colombia', 'coffee', 1700, 22,
 'Medium roast decaf, 12 oz (340 g) whole bean. Decaffeinated with the Swiss Water Process. Caramel and almond, with a smooth body that holds up in any brew method.'),
('EO-COF-010', 'Cold Brew Blend', 'coffee', 1500, 47,
 'Medium roast blend chosen for cold brew, 12 oz (340 g) whole bean. Chocolate, molasses and a hint of citrus. Also available ground coarse at checkout for immersion brewing.'),
('EO-GEAR-101', 'Ceramic Pour-Over Dripper (size 02)', 'gear', 2800, 25,
 'Cone shaped ceramic dripper for one to four cups. Ribbed walls for even flow. Uses size 02 paper filters. Dishwasher safe.'),
('EO-GEAR-102', 'Glass French Press 34 oz', 'gear', 3400, 18,
 'Borosilicate glass carafe with a stainless steel frame and a fine mesh plunger. Brews up to four mugs. Dishwasher safe.'),
('EO-GEAR-103', 'Manual Burr Grinder', 'gear', 5900, 9,
 'Hand crank grinder with stainless steel conical burrs and stepped grind adjustment from espresso to coarse. Holds about 30 g of beans. Quiet and portable. 2 year warranty.'),
('EO-GEAR-104', 'Electric Burr Grinder', 'gear', 12900, 4,
 'Flat burr electric grinder with 40 grind settings from espresso to cold brew. Hopper holds 250 g. Includes a small brush. 2 year warranty.'),
('EO-GEAR-105', 'Stainless Moka Pot 6-cup', 'gear', 3600, 14,
 'Stovetop moka pot in stainless steel, makes about 300 ml. Works on gas, electric and induction hobs.'),
('EO-GEAR-106', 'Gooseneck Kettle 1 L', 'gear', 5400, 11,
 'Stainless steel gooseneck kettle for controlled pouring. 1 litre capacity. Works on gas and electric hobs; the base is not induction compatible.'),
('EO-GEAR-107', 'Digital Coffee Scale', 'gear', 3500, 20,
 'Scale with a built in timer, 0.1 g resolution and 2 kg capacity. Rechargeable over USB-C.'),
('EO-GEAR-108', 'Travel Press Mug 12 oz', 'gear', 2600, 30,
 'Insulated stainless steel travel mug with a built in press plunger, 12 oz. Brew and carry in one cup.'),
('EO-GEAR-109', 'Glass Carafe Server 600 ml', 'gear', 3000, 16,
 'Heat resistant glass carafe with a lid, 600 ml. Pairs with the pour-over dripper to serve two to three cups.'),
('EO-ACC-201', 'Paper Filters size 02 (100 count)', 'accessory', 900, 150,
 'Unbleached paper filters for cone shaped size 02 drippers. Pack of 100.'),
('EO-ACC-202', 'Reusable Steel Filter', 'accessory', 1800, 35,
 'Fine mesh stainless steel cone filter that fits size 02 drippers. Produces a slightly heavier cup than paper.'),
('EO-ACC-203', 'Descaling Kit', 'accessory', 1200, 60,
 'Citric acid descaler for kettles and moka pots. Three uses per pack. Not suitable for espresso machines that need a manufacturer approved descaler.'),
('EO-SUB-301', 'Monthly Coffee Subscription (one 12 oz bag)', 'subscription', 1350, 999,
 'Choose any one coffee and receive it on a schedule of every 2, 3 or 4 weeks. 10 percent below the single bag price and free standard shipping. Skip, pause or cancel any time.'),
('EO-GIFT-401', 'Tasting Set (four 3 oz bags)', 'gift', 2400, 28,
 'Four 3 oz (85 g) bags: Ethiopia Guji Natural, Colombia Huila Washed, Brazil Cerrado and Ember House Blend. Packed in a gift box with a brewing card. A gift note can be added at checkout.');

insert into public.orders (order_number, customer_email, status, placed_at, carrier, tracking_number, estimated_delivery, total_cents) values
('EO-10001', 'maya.lopez@example.com',   'delivered',  now() - interval '12 days', 'UPS',  '1ZEO0001DEMO0001', (now() - interval '8 days')::date,  3500),
('EO-10002', 'sam.okafor@example.com',   'shipped',    now() - interval '3 days',  'USPS', '9400EODEMO0000002', (now() + interval '2 days')::date, 5950),
('EO-10003', 'priya.nair@example.com',   'roasting',   now() - interval '1 day',   null,   null,               (now() + interval '4 days')::date, 1850),
('EO-10004', 'liam.chen@example.com',    'processing', now() - interval '3 hours', null,   null,               (now() + interval '5 days')::date, 2800),
('EO-10005', 'ana.silva@example.com',    'delivered',  now() - interval '20 days', 'UPS',  '1ZEO0005DEMO0005', (now() - interval '15 days')::date, 12900),
('EO-10006', 'noah.baker@example.com',   'cancelled',  now() - interval '6 days',  null,   null,               null,                              3300),
('EO-10007', 'zoe.martin@example.com',   'refunded',   now() - interval '25 days', 'USPS', '9400EODEMO0000007', (now() - interval '20 days')::date, 1700),
('EO-10008', 'omar.haddad@example.com',  'shipped',    now() - interval '2 days',  'UPS',  '1ZEO0008DEMO0008', (now() + interval '1 day')::date,   4300),
('EO-10009', 'emma.wright@example.com',  'roasting',   now() - interval '5 hours', null,   null,               (now() + interval '4 days')::date, 2900),
('EO-10010', 'lucas.meyer@example.com',  'delivered',  now() - interval '9 days',  'USPS', '9400EODEMO0000010', (now() - interval '5 days')::date, 2400),
('EO-10011', 'nina.rossi@example.com',   'shipped',    now() - interval '1 day',   'UPS',  '1ZEO0011DEMO0011', (now() + interval '3 days')::date,  6100),
('EO-10012', 'kofi.mensah@example.com',  'processing', now() - interval '30 minutes', null, null,              (now() + interval '5 days')::date, 1450),
('EO-10013', 'ivy.tanaka@example.com',   'delivered',  now() - interval '15 days', 'UPS',  '1ZEO0013DEMO0013', (now() - interval '10 days')::date, 8300),
('EO-10014', 'diego.perez@example.com',  'roasting',   now() - interval '2 hours', null,   null,               (now() + interval '4 days')::date, 3200);

insert into public.order_items (order_id, sku, qty)
select o.id, v.sku, v.qty
from (values
  ('EO-10001', 'EO-COF-002', 1), ('EO-10001', 'EO-ACC-201', 1), ('EO-10001', 'EO-COF-007', 1),
  ('EO-10002', 'EO-GEAR-103', 1),
  ('EO-10003', 'EO-COF-001', 1),
  ('EO-10004', 'EO-GEAR-101', 1),
  ('EO-10005', 'EO-GEAR-104', 1),
  ('EO-10006', 'EO-COF-004', 2),
  ('EO-10007', 'EO-COF-009', 1),
  ('EO-10008', 'EO-GEAR-102', 1), ('EO-10008', 'EO-COF-007', 1),
  ('EO-10009', 'EO-COF-005', 1), ('EO-10009', 'EO-COF-008', 1),
  ('EO-10010', 'EO-GIFT-401', 1),
  ('EO-10011', 'EO-GEAR-106', 1), ('EO-10011', 'EO-COF-003', 1),
  ('EO-10012', 'EO-COF-007', 1),
  ('EO-10013', 'EO-GEAR-103', 1), ('EO-10013', 'EO-COF-002', 1), ('EO-10013', 'EO-COF-001', 1),
  ('EO-10014', 'EO-COF-008', 2)
) as v (order_number, sku, qty)
join public.orders o on o.order_number = v.order_number;
